# Generated by Django 3.2.7 on 2021-11-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='description',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='name',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='price',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='tags',
        ),
    ]
