# Generated by Django 3.2.7 on 2021-11-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_arriving_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='email',
            new_name='parents_Number',
        ),
    ]
