# Generated by Django 3.2.7 on 2021-11-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211115_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arriving',
            old_name='passenger',
            new_name='passenger_name',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='parents_number',
            new_name='parents_Number',
        ),
    ]
