# Generated by Django 3.2.7 on 2021-11-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211115_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arriving',
            old_name='product',
            new_name='grade',
        ),
    ]
