# Generated by Django 3.2.7 on 2021-11-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_product_arriving_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grade',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='arriving',
            old_name='grade',
            new_name='age',
        ),
    ]
