# Generated by Django 3.2.7 on 2021-11-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_category_age_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age',
            old_name='status',
            new_name='age',
        ),
    ]
