# Generated by Django 3.2.7 on 2021-11-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_status_age_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age',
            old_name='age',
            new_name='status',
        ),
    ]
