# Generated by Django 3.2.7 on 2021-11-15 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211115_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age',
            old_name='status',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='arriving',
            name='age',
            field=models.ForeignKey(choices=[('Kid', 'Kid'), ('Adult', 'Adult')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.age'),
        ),
    ]
