# Generated by Django 3.2.7 on 2021-11-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211115_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriving',
            name='status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Off the bus', 'Off the bus')], max_length=200, null=True),
        ),
    ]
