# Generated by Django 3.2.7 on 2021-11-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_arriving_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriving',
            name='status',
            field=models.CharField(choices=[('On the bus', 'On the bus'), ('Off the bus', 'Off the bus')], max_length=200, null=True),
        ),
    ]
