# Generated by Django 3.2.7 on 2021-11-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_arriving_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='parents_Number',
            new_name='preferred_Number',
        ),
    ]
