# Generated by Django 3.2.7 on 2021-11-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_arriving_passenger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriving',
            name='passenger_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.passenger'),
        ),
    ]
