# Generated by Django 3.2.7 on 2021-11-18 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_arriving_passenger_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_name',
        ),
    ]
